name:                fundamental
version:             0.1.0.0
github:              "prosumma/hs-fundamental"
license:             MIT
author:              "Gregory Higley"
maintainer:          "greg@prosumma.com"
copyright:           "2026 Prosumma / Gregory Higley"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fundamental#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- composition-prelude
- extra
- formatting
- generic-lens
- lens
- listsafe
- mtl
- postgresql-simple
- resource-pool
- rio
- servant-auth
- servant-auth-server
- servant-client
- servant-server
- string-conversions
- template-haskell
- text

default-extensions:
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeSynonymInstances

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fundamental-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fundamental

tests:
  fundamental-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fundamental
